name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: jamescurtin/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements-dev.txt"
      - run: find . -name '*.py' -print0 | xargs -0 pyupgrade --py36-plus
